url: 1995re.github.io
disqus_shortname: bahasalien

title: +
description: ðŸ“‘
theme: jekyll-theme-tactile

# This will require each of these plugins automatically.
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-import
